inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact
Style/HashSyntax:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
