name: Track codebase stats

on:
  push:
    branches:
      - main

jobs:
  cherry_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: npm install

      - name: Push metrics
        run: ./bin/cherry.js push --api-key=${{ secrets.CHERRY_API_KEY }}
