name: cherry push

on:
  push:
    branches: [main]

jobs:
  cherry_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install dependencies
        run: npm install

      - name: Push metrics
        run: ./bin/cherry.js push --quiet --api-key=${{ secrets.CHERRY_API_KEY }}
