name: Cherry Push

on:
  push:
    branches:
      - main

jobs:
  cherry:
    name: Push metrics and contributions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          bundle install
          npm install
          npm install -g cherrypush

      - name: Push metrics
        run: cherry push --api-key=${{ secrets.CHERRY_API_KEY }}
